using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FinanceAPI.Migrations
{
    /// <inheritdoc />
    public partial class FixTransactionsSchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Corrige a coluna Id para ser Identity (Auto-incremento no Postgres)
            // Se já houver restrição, o Postgres retornará erro, então usamos um bloco para tentar resolver.
            migrationBuilder.Sql("ALTER TABLE \"Transactions\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");
        }


        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
