using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FinanceAPI.Migrations
{
    /// <inheritdoc />
    public partial class AddUserIdToTransactions : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Tenta adicionar a coluna UserId (caso não exista por erro de sincronismo anterior)
            migrationBuilder.Sql("ALTER TABLE \"Transactions\" ADD COLUMN IF NOT EXISTS \"UserId\" text;");

            // Corrige a coluna Id para ser Identity (Auto-incremento no Postgres)
            // Nota: Se já houver restrição, o IF NOT EXISTS ou o tratamento de erro manual ajuda.
            migrationBuilder.Sql("ALTER TABLE \"Transactions\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");
        }



        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
