apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-ledger-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finance-ledger
  template:
    metadata:
      labels:
        app: finance-ledger
    spec:
      containers:
      - name: finance-ledger-api
        image: guilhermerondon/finance-ledger:latest # Placeholder da imagem
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
---
apiVersion: v1
kind: Service
metadata:
  name: finance-ledger-service
spec:
  type: ClusterIP
  selector:
    app: finance-ledger
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
